name: Deploy Writerside to GitHub Pages

on:
  push:
    branches:
      - main  # 监听 main 分支的推送事件

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Build docs using Writerside Docker builder
      uses: JetBrains/writerside-github-action@v4
      with:
        instance: 'Writerside/aw'  # 根据你的项目配置调整此值
        artifact: 'webHelpAW2-all.zip'  # 根据你的项目配置调整此值
        docker-version: '242.21870'  # 使用最新的 Docker 版本

    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./artifacts/webHelpAW2-all  # 指定要发布的目录
